#!/bin/bash

echo "🔍 Finding Your Stripe Connect Client ID"
echo "=========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://dashboard.stripe.com"
echo "2. Click 'Settings' in the left sidebar"
echo "3. Click 'Connect' (under Settings)"
echo ""
echo "If you see 'Connect platform settings':"
echo "  → Look for 'Client ID' (starts with ca_)"
echo ""
echo "If you DON'T see Connect:"
echo "  → Click 'Get Started' or 'Enable Connect'"
echo "  → Choose 'Standard accounts'"
echo "  → Complete the setup wizard"
echo "  → Then the Client ID will appear"
echo ""
echo "Alternative location:"
echo "  → Developers → Connect"
echo ""
echo "The Client ID format: ca_xxxxxxxxxxxxx"
echo ""
